/// <reference path="jquery-2.1.0.intellisense.js" />
// Temprorarily needed for intellisense
/// <reference path="ExchangeClient.js" />
/// <reference path="ADAL.js" />

var authContext;
var authtoken;


function ReadUnreadEmails() {
//    var rest = "hi, i am sunny";
//    alert(cordova);
//    alert(cordova.exe);
//    cordova.exec(function (data) {
//    }, function (err) {
//        alert(err);
//    },
//"Device", "TextTospeech", [rest]);
    if (!authContext) {
        authContext = new O365Auth.Context();
    }

    authContext.getIdToken("https://outlook.office365.com/")
        .then((function (token) {
            authtoken = token;
            //getEvents();
            ReadUnreadEmailsPrivate();
        }).bind(this), function (reason) {
            $('#error').text('failed ' + reason.message);
        });
}

function ReadUnreadEmailsPrivate() {
    var accessToken = authtoken.getAccessTokenFn('https://outlook.office365.com');
    
    accessToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1THdqcHdBSk9NOW4tQSJ9.eyJhdWQiOiJodHRwczovL291dGxvb2sub2ZmaWNlMzY1LmNvbS8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83M2I3OGU4MC0wZDU3LTQyODUtODc5OC01MTdlN2YxNzhkNWQvIiwiaWF0IjoxMzk5MTQ1OTk1LCJuYmYiOjEzOTkxNDU5OTUsImV4cCI6MTM5OTE0OTg5NSwidmVyIjoiMS4wIiwidGlkIjoiNzNiNzhlODAtMGQ1Ny00Mjg1LTg3OTgtNTE3ZTdmMTc4ZDVkIiwiYW1yIjpbInB3ZCJdLCJvaWQiOiI4MmY4NmM3ZS0xYzIwLTQ1ZDQtOGMxZS0zNjkwZTA2YjM1ZWEiLCJ1cG4iOiJzdWd1cHRheGJveEBzdWd1cHRhY29ycC5vbm1pY3Jvc29mdC5jb20iLCJ1bmlxdWVfbmFtZSI6InN1Z3VwdGF4Ym94QHN1Z3VwdGFjb3JwLm9ubWljcm9zb2Z0LmNvbSIsInN1YiI6IjZtYlhNYmJIOFNGWGp5dHpjakFEWmRkWWgxQ1FvMGhVaTJ6Z3pfZHNJMFUiLCJwdWlkIjoiMTAwMzAwMDA4OTY1QkY2QSIsImZhbWlseV9uYW1lIjoiR3VwdGEiLCJnaXZlbl9uYW1lIjoiU3VubnkiLCJhcHBpZCI6IjE0Y2Q2MDdiLTgxYWUtNGRkMi1hOTVhLWY2NDEyNmIxMjFiZSIsImFwcGlkYWNyIjoiMCIsInNjcCI6Ik1haWwuU2VuZCBNYWlsLldyaXRlIE1haWwuUmVhZCIsImFjciI6IjEifQ.FFVcCfBinFW96LyYJ0zh2iquS_W1qHiZ7pMYSafzChokDpQKSx_k1N-mXu6xHI-kEGqCVYQailWnAn7PDDelQU1sTZuiOVywu3xEnJTVx_bcogegUfhaD6l-7TAek2sCrvms8akWgL6wr-ZBHs-S7KIy1YH7JIOBSz5REpHTNJzkmY-lIsQM6QNuWwKEOjYQrxVjoiEqtiydV56C8DFQOkITfAkoHay6p1_RSWzYFvmcBfY6_4Pq6U_hcpIJ6VJtqoLDI6Ut9x9ebNdc9ObwZ2uK5zY5RTVyVAmOYVZKfbwY8gB3HkkmWFjbs0U5SF5ofO1KpcnB4Kor3Beu2HeVpw";
    var ExchangeMailUrl = "https://outlook.office365.com/ews/odata/Me/Inbox/Messages";
    ExchangeMailUrl = ExchangeMailUrl + "?$orderby=DateTimeSent desc&$top=20&$select=Subject,DateTimeReceived,From";
    $.ajax({
        type: 'GET',
        url: ExchangeMailUrl,
        headers: {
            "Authorization": "Bearer " + accessToken,
            "Accept": "application/json;odata=minimalmetadata"
        },
        dataType: 'json',
        success: function (responseData, textStatus, jqXHR) {
            var jsonResponse = responseData.value;
            var rest = "You have " + jsonResponse.length + " unread emails. Here they are: ";
            for (var i = 0; i < jsonResponse.length; i++) {
                console.log(jsonResponse[i].Subject);
                console.log(jsonResponse[i].DateTimeReceived);
                console.log(jsonResponse[i].From.Name);
                var fromText = " From:"     + jsonResponse[i].From.Name + ",";
                var subject =  " Subject:"  + jsonResponse[i].Subject   + ".";
                rest = rest + fromText + subject;
                //rest = " " + rest + jsonResponse[i].Subject + " " + 
            }

            cordova.exec(function (data) {
            }, function (err) {
                alert(err);
            },
            "Device", "TextTospeech", [rest]);
        },
        error: function (responseData, textStatus, errorThrown) {
            alert('GET Email failed.');
        }
    });



    //var ec2 = new Exchange.Client('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    //ec2.Me.Calendar.Events.getEventCollection()
    //            .then(function (Events) {
    //                var events = Events.currentPage;
    //                displayEvents(events);
    //            }, function (reason) {
    //                $('#error').text('failed ' + reason);
    //            });

    //var ec = new Exchange.Client('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));

    //ec.Me.Messages.getMessage('suguptaxbox@suguptacorp.onmicrosoft.com');

    //var message = Exchange.Message();
    //message.Subject = 'Autogenerated Email';

    //message.Body = new Exchange.ItemBody();
    //message.Body.Content = 'This is a test email';
    //message.Body.ContentType = 'HTML';//Microsoft.Exchange.Services.OData.Model.BodyType.Text;

    //var recipient = Microsoft.Exchange.Services.OData.Model.Recipient.create();
    //recipient.Address = 'cltestuser@napaprod11.onmicrosoft.com';
    //recipient.Name = 'Saurabh';
    //message.ToRecipients = [recipient];

    //var ec = new Microsoft.Exchange.Services.OData.Model.ExchangeClient('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    //ec.Me.Messages.addMessage(message);



    // var message = new Exchange.Message();
    // message.Subject = 'Autogenerated Email';
    //// message.From = new Exchange.Recipient({ address: "suguptaxbox@sugutacorp.onmicrosoft.com" });
    // message.Body = new Exchange.ItemBody({ Content: 'This is a test email', ContentType: "HTML" });

    // message.ToRecipients = [new Exchange.Recipient({ Address: "suguptaxbox@suguptacorp.onmicrosoft.com" })];

    // var ec = new Exchange.Client('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    // ec.Me.Messages.addMessage(message);
}

function displayEvents(events) {
    showEvents();
    var eventsList = $('#calendarEvents');
    eventsList.empty();

    for (var i = 0; i < events.length; i++) {
        (function (index, self) {
            var event = $('<li>' + events[index].Subject + '</li>');
            event.on('click', (function (e) {
                self.getEvent(events[index].Id);
            }).bind(this));
            eventsList.append(event);
        })(i, this);
    }
}


function showEvents() {
    $('#error').text('');
    $('#AadLogin').hide();
    $('#calendarEvents').show();
    $('#calendarEvent').hide();
    $('#calendarBack').hide();
}

function getEvent(id) {
    var ec = new Microsoft.Exchange.Services.OData.Model.ExchangeClient('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    ec.Me.Calendar.exec()
        .then(function (Calendar) {
            var event = Calendar.Events.getEvent(id);
            event.exec()
               .then(function (event) {
                   displayEvent(event);
               }, function (reason) {
                   $('#error').text('failed ' + reason);
               });
        }, function (reason) {
            $('#error').text('failed ' + reason);
        });

}



function displayEvent(event) {
    this.showEvent();

    var eventList = $('#calendarEvent');

    eventList.empty();

    eventList.append('<li>Subject: ' + event.Subject + '</li>');
    eventList.append('<li>Start Time: ' + event.Start + '</li>');
    eventList.append('<li>End Time: ' + event.End + '</li>');
    if (event.Body) {
        var msgbody = document.createElement("div");
        msgbody.innerHTML = event.Body.Content;
        eventList.append('<li>Body: ' + msgbody.innerText + '</li>');
    }
    if (event.Location) {
        eventList.append('<li>Location: ' + event.Location.DisplayName + '</li>');
    }
}

function showEvent() {
    $('#error').text('');
    $('#AadLogin').hide();
    $('#calendarEvents').hide();
    $('#calendarEvent').show();
    $('#calendarBack').show();
}


function logout() {
    if (!authContext) {
        authContext = new O365Auth.Context();
    }

    authContext.logOut();
    authtoken = '';
    $('#error').text('');
    $('#AadLogin').show();
    $('#calendarBack').hide();
    $('#calenderEvents').hide();
    $('#calendarEvent').hide();
}


function sendMail() {
    var message = Microsoft.Exchange.Services.OData.Model.Message.create();
    message.Subject = 'Autogenerated Email';

    message.Body = Microsoft.Exchange.Services.OData.Model.ItemBody.create();
    message.Body.Content = 'This is a test email';
    message.Body.ContentType = Microsoft.Exchange.Services.OData.Model.BodyType.Text;

    var recipient = Microsoft.Exchange.Services.OData.Model.Recipient.create();
    recipient.Address = 'cltestuser@napaprod11.onmicrosoft.com';
    recipient.Name = 'Saurabh';
    message.ToRecipients = [recipient];

    var ec = new Microsoft.Exchange.Services.OData.Model.ExchangeClient('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    ec.Me.Messages.addMessage(message);
}

function addEvent() {
    var myevent = Microsoft.Exchange.Services.OData.Model.Event.create();
    myevent.Subject = 'Test Event';
    myevent.Body = Microsoft.Exchange.Services.OData.Model.ItemBody.create();
    myevent.Body.Content = 'This is sample content';
    myevent.Body.ContentType = Microsoft.Exchange.Services.OData.Model.BodyType.Text;
    var attendee = Microsoft.Exchange.Services.OData.Model.Attendee.create();
    attendee.Address = 'cltestuser@napaprod11.onmicrosoft.com';
    myevent.Attendees = [attendee];
    var ec = new Microsoft.Exchange.Services.OData.Model.ExchangeClient('https://outlook.office365.com/ews/odata', authtoken.getAccessTokenFn('https://outlook.office365.com'));
    ec.Me.Events.addEvent(myevent);
    getEvents();
}


// Optionallly if you don’t want to add initialization code in index.js (makes for faster demos)
/*$(document).ready(function () {

    $('#calendarEvents').hide();
    $('#calendarEvent').hide();
    $('#calendarBack').hide();

    $('#AadLogin').click(login);
    $('#AadLogout').click(logout);
    $('#calendarBack').click(showEvents);
    $('#sendMail').click(sendMail);
    $('#addEvent').click(addEvent);

});
*/
